---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: core
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: <ARGO_WORKFLOWS_VERSION>
    helm:
      valuesObject:
        commonLabels:
          <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
          <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          <PLATFORM_NAME_KEBAB>.metadata.service: continuous-integration.argo-workflow
          <PLATFORM_NAME_KEBAB>.metadata.chart-version: <ARGO_WORKFLOWS_VERSION>
          <PLATFORM_NAME_KEBAB>.metadata.version: 3.6.7
        singleNamespace: false
        nameOverride: argo
        controller:
          instanceID:
            enabled: true
            explicitID: "<PLATFORM_NAME>"
          workflowDefaults:
            spec:
              podGC:
                strategy: OnWorkflowSuccess
              ttlStrategy:
                secondsAfterCompletion: 43200
                secondsAfterSuccess: 1800
                secondsAfterFailure: 21600
          rbac:
            create: true
          workflowNamespaces: [argo]
          image:
            registry: "<REGISTRY_INGRESS_URL>/quay-proxy"
            repository: "argoproj/workflow-controller"
        images:
          pullPolicy: IfNotPresent
          pullSecrets:
            - name: proxy-docker-config
            - name: docker-config
        mainContainer:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
        executor:
          image:
            registry: "<REGISTRY_INGRESS_URL>/quay-proxy"
            repository: "argoproj/argoexec"
            pullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 1Gi
        workflow:
          serviceAccount:
            pullSecrets:
              - name: proxy-docker-config
            create: true
          rbac:
            create: true
        server:
          image:
            registry: "<REGISTRY_INGRESS_URL>/quay-proxy"
            repository: "argoproj/argocli"
          authMode: sso
          secure: false
          serviceAccount:
            create: true
            name: argo-server
            annotations:
              <K8S_ROLE_MAPPING>: "<CI_IAM_ROLE_RN>"
          rbac:
            create: true
          extraEnv:
            - name: SSO_DELEGATE_RBAC_TO_NAMESPACE
              value: 'true'
          ingress:
            enabled: false
          sso:
            enabled: true
            issuer: https://<OIDC_PROVIDER_URL>
            clientId:
              name: argo-secrets
              key: client-id
            clientSecret:
              name: argo-secrets
              key: client-secret
            redirectUrl: https://<CI_OAUTH_CALLBACK_URL>
            scopes: [email, openid, groups, user, profile]
            rbac:
              enabled: true
        useDefaultArtifactRepo: false
        useStaticCredentials: false
    chart: argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [CreateNamespace=true]
