apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-<PLATFORM_NAME>
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  replicas: 2
  template:
    spec:
      organization: <GIT_ORGANIZATION_NAME>
      image: summerwind/actions-runner-dind
      serviceAccountName: github-runner
      dockerdWithinRunnerContainer: true
      automountServiceAccountToken: true
      # set runner group name when GitHub is on non-free plan
      # <GIT_RUNNER_GROUP>
