apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
  <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
  <PLATFORM_NAME_KEBAB>.metadata.service: proxy.oauth2
  <PLATFORM_NAME_KEBAB>.metadata.version: latest

resources:
- oauth2-proxy.yaml
- oauth2-proxy-ing.yaml
- externalsecrets.yaml

generatorOptions:
  disableNameSuffixHash: true
