---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perfectscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "180"
spec:
  project: core
  source:
    repoURL: https://perfectscale-io.github.io
    chart: exporter
    targetRevision: v1.0.41
    helm:
      values: |-
        secret:
          name: perfectscale-secret
        settings:
          clusterName: <PRIMARY_CLUSTER_NAME>-perfectscale
        additionalLabels: 
          <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
          <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          <PLATFORM_NAME_KEBAB>.metadata.service: scaler.perfectscale
          <PLATFORM_NAME_KEBAB>.metadata.chart-version: 1.0.41
          <PLATFORM_NAME_KEBAB>.metadata.version: 1.0.0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: perfectscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psc-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "180"
spec:
  project: core
  source:
    repoURL: https://perfectscale-io.github.io
    chart: psc-autoscaler
    targetRevision: v1.0.10
    helm:
      values: |-
        secret:
          create: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: perfectscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
